import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const API='http://localhost:8787';
const agents=[['prometheus','PROMETHEUS','ORCHESTRATOR'],['nexus','NEXUS','ENGINEERING'],['researcher','RESEARCHER','INTELLIGENCE'],['ceo','CEO','BUSINESS'],['carrot','CARROT','TRAINING'],['susan','SUSAN','SECRETARY'],['offline','OFFLINE','LOCAL']];

function App(){
 const [selected,setSelected]=useState('prometheus'),[view,setView]=useState('core'),[text,setText]=useState(''),[messages,setMessages]=useState([]),[missions,setMissions]=useState([]),[approvals,setApprovals]=useState([]),[listening,setListening]=useState(false),[status,setStatus]=useState('RUNTIME OFFLINE'),[boot,setBoot]=useState(true),rec=useRef(null);
 useEffect(()=>{const timer=setTimeout(()=>setBoot(false),1900);fetch(API+'/api/health').then(r=>r.ok&&setStatus('RUNTIME ONLINE')).catch(()=>{});const t=setInterval(()=>fetch(API+'/api/state').then(r=>r.json()).then(d=>{setMissions(d.missions||[]);setApprovals((d.approvals||[]).filter(x=>x.status==='pending'))}).catch(()=>{}),2000);return()=>{clearTimeout(timer);clearInterval(t)}},[]);
 function speak(s){if(!speechSynthesis)return;speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(s))}
 async function send(){if(!text.trim())return;const q=text.trim();setMessages(m=>[...m,{from:'YOU',text:q}]);setText('');try{const r=await fetch(API+'/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({agentId:selected,text:q,history:messages.slice(-8).map(m=>({role:m.from==='YOU'?'user':'assistant',content:m.text}))})});const d=await r.json();const answer=d.answer||d.error||'No response.';setMessages(m=>[...m,{from:selected.toUpperCase(),text:answer}]);speak(answer)}catch(e){setMessages(m=>[...m,{from:'SYSTEM',text:'Runtime unavailable. Start the Prometheus server on port 8787.'}])}}
 async function mission(agent,prompt,title){try{await fetch(API+'/api/mission',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({agentId:agent,prompt,title})});setView('missions')}catch(e){}}
 async function approval(id,decision){await fetch(API+'/api/approval',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,decision})})}
 function voice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert('Voice recognition is unavailable in this browser.');if(listening){rec.current.stop();return}const x=new R();rec.current=x;x.lang='en-US';x.interimResults=false;x.onstart=()=>setListening(true);x.onend=()=>setListening(false);x.onresult=e=>{setText(e.results[0][0].transcript);setTimeout(send,50)};x.start()}
 const task=a=>a==='nexus'?'FULL-STACK ENGINEERING':a==='researcher'?'EVIDENCE RESEARCH':a==='ceo'?'COMPANY STRATEGY':a==='carrot'?'TRAINING & KNOWLEDGE':a==='susan'?'DAILY OPERATIONS':a==='offline'?'LOCAL PC AUTOMATION':'ORCHESTRATION & ADVICE';
 return <main className="os-shell">
  {boot&&<div className="boot-screen"><div className="boot-brand">PROMETHEUS</div><div className="boot-lines"><span>&gt; INITIALIZING AI KERNEL... [OK]</span><span>&gt; LOADING NEURAL MATRIX... [OK]</span><span>&gt; ESTABLISHING VOICE LINK... [OK]</span><span>&gt; MOUNTING ROUNDTABLE... [OK]</span><span>&gt; PROMETHEUS CORE ONLINE.</span></div><div className="boot-cursor">_</div></div>}
  <header className="topbar"><div><div className="eyebrow">PROMETHEUS // CORE OS v1.0</div><h1>THE ROUNDTABLE</h1></div><div className="system-state"><span className="pulse"/> {status}<span className="divider"/>CPU: LOCAL<span className="divider"/>7 AGENTS<span className="divider"/>ROUTER</div></header>
  <nav className="mode-bar"><button className={view==='core'?'active':''} onClick={()=>setView('core')}>◈ CORE</button><button className={view==='council'?'active':''} onClick={()=>setView('council')}>◉ COUNCIL</button><button className={view==='missions'?'active':''} onClick={()=>setView('missions')}>◫ MISSIONS</button></nav>
  <section className="hud-grid">
   <aside className="panel terminal-panel"><div className="panel-header">SYS.01 // COMMAND TERMINAL</div><div className="term-output">{messages.length?messages.slice(-12).map((m,i)=><div className={m.from==='YOU'?'term-user':'term-ai'} key={i}><b>{m.from==='YOU'?'USR>':'AI>'}</b> {m.text}</div>):<><div className="term-ai">PROMETHEUS AI ONLINE.</div><div className="term-sys">Voice link awaiting operator input...</div><div className="term-sys">Type a command below or use the core microphone.</div></>}</div><div className="term-input"><span>USR&gt;</span><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="COMMAND..."/><button onClick={send}>↵</button></div></aside>
   <section className="panel core-panel"><div className="panel-header core-header">SYS.02 // HIGH-DENSITY NEURAL CORE</div><div className={'neural-orb '+(listening?'listening':'')} onClick={voice}><div className="orb-halo halo-one"/><div className="orb-halo halo-two"/><div className="orb-grid"/><div className="orb-rune">ᚱ</div><div className="orb-core"><span>◉</span></div><div className="orb-label">{listening?'LISTENING':'PROMETHEUS'}</div></div><div className="core-status">PARTICLE MATRIX ACTIVE // VOICE LINK {listening?'OPEN':'STANDBY'}</div><div className="core-command">{text||'Speak to Prometheus.'}</div><div className="core-actions"><button onClick={voice}>{listening?'STOP VOICE':'ACTIVATE VOICE'}</button><button onClick={()=>setView('council')}>SUMMON COUNCIL</button><button onClick={()=>mission('researcher','Research the requested topic with verified sources and return a concise evidence report.','Research mission')}>RESEARCH</button></div></section>
   <aside className="panel sensors-panel"><div className="panel-header">SYS.03 // GLOBAL SENSORS</div><div className="globe"><div className="globe-lat lat1"/><div className="globe-lat lat2"/><div className="globe-long long1"/><div className="globe-long long2"/><div className="globe-dot dot1"/><div className="globe-dot dot2"/><div className="globe-dot dot3"/><span>GLOBAL GRID</span></div><div className="sensor-readout"><div><span>NET</span><b>SECURE</b></div><div><span>MODEL</span><b>ROUTER</b></div><div><span>VOICE</span><b>{listening?'ACTIVE':'READY'}</b></div></div><div className="radar"><i/><i/><i/><span/></div></aside>
  </section>
  {view==='council'&&<section className="lower-section"><div className="section-title">SYS.04 // AGENT COUNCIL</div><div className="agent-grid">{agents.map(a=><button className={'agent-card '+(selected===a[0]?'selected':'')} onClick={()=>setSelected(a[0])} key={a[0]}><div className="card-head"><div className="agent-icon">◈</div><div className="agent-meta"><strong>{a[1]}</strong><span>{a[2]}</span></div><span className="status"><i/> READY</span></div><div className="task">{task(a[0])}</div></button>)}</div></section>}
  {view==='missions'&&<section className="lower-section"><div className="section-title">SYS.05 // BACKGROUND MISSIONS</div><div className="mission-board">{missions.length?missions.map(m=><div className="mission" key={m.id}><div className="mission-head"><strong>{m.agentId.toUpperCase()}</strong><span>{m.status.toUpperCase()}</span></div><h3>{m.title}</h3><p>{m.prompt}</p><div className="progress"><span style={{width:m.progress+'%'}}/></div>{m.result&&<pre>{m.result}</pre>}</div>):<div className="empty">NO BACKGROUND MISSIONS.</div>}</div></section>}
  <section className="bottom-grid"><div className="panel feed"><div className="panel-header">SYS.06 // VOICE FEED</div><div className="feed-scroll">{messages.length?messages.map((m,i)=><div className="message" key={i}><span>{m.from}</span><p>{m.text}</p></div>):<div className="empty">VOICE FEED READY.</div>}</div></div><aside className="panel inspector"><div className="panel-header">SYS.07 // OPERATOR</div><h2>{selected.toUpperCase()}</h2><div className="role">{agents.find(a=>a[0]===selected)?.[2]}</div><p>Memory, tools and model routing are managed by the Prometheus runtime.</p>{approvals.length>0&&<div className="approvals"><h4>APPROVAL PLANE</h4>{approvals.map(a=><div className="approval" key={a.id}><small>{a.action}</small><button onClick={()=>approval(a.id,'allow')}>ALLOW</button><button onClick={()=>approval(a.id,'deny')}>DENY</button></div>)}</div>}</aside></section>
  <footer className="hud-footer"><span>BACKGROUND OPERATIONS</span><span>APPROVAL PLANE</span><span>MODEL ROUTER</span><span>NO-FABRICATION POLICY</span><span>PROMETHEUS CORE</span></footer>
 </main>
}
createRoot(document.getElementById('root')).render(<App/>);